### ISSUE TITLE
InvalidFormatException is thrown when a malformed link is present in an RSS feed

### ISSUE THREAD

**Issue by Kolomona** [yusufyilmazfr/podcast4j#5]
When running the test getPodcastsByMedium_shouldReturnMatchedPodcast()

I'm getting the following error. I believe this is due to no "http://" or "https://" in the beginning of the link "www.aikihomestead.ca" 

The offending podcast is at https://podcastindex.org/podcast/6786261

`com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.net.URL` from String "www.aikihomestead.ca": not a valid textual representation, problem: no protocol: www.aikihomestead.ca`

I'll try to track down a solution but I'm not very familiar with com.fasterxml.jackson

There should be a way to assume a protocol such as http or https.

**Comment by yusufyilmazfr** [comment]
Hello @Kolomona, I've changed URL data type to string because of we don't have to deal with podcastindex API response consistency so we'll never take a exception about malformed link. And I've added some deserialization settings in project. I don't expect any unknown field exception.

**Comment by yusufyilmazfr** [comment]
These problems are fixed! New client is available on central repositories. 🎧

```xml
<dependencies>
    <dependency>
        <groupId>io.github.yusufyilmazfr</groupId>
        <artifactId>podcast4j</artifactId>
        <version>1.0.2</version>
    </dependency>
</dependencies>
```
